basic.showIcon(IconNames.EigthNote)
basic.forever(function () {
    soundExpression.giggle.playUntilDone()
    basic.pause(1000)
    soundExpression.happy.playUntilDone()
    basic.pause(1000)
    soundExpression.hello.playUntilDone()
    basic.pause(1000)
    soundExpression.yawn.playUntilDone()
    basic.pause(1000)
})
